version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: cimg/go:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run: make image
      - deploy:
          command: |
            if [[ "$CIRCLE_BRANCH" == "master" ]]; then
              docker tag ctop quay.io/vektorlab/ctop:latest
              docker tag ctop quay.io/vektorlab/ctop:$(cat VERSION)
              docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io
              docker push quay.io/vektorlab/ctop
            fi
